
<!--On charge le header-->
<?php $this->view("portfolio/header", $data); ?>

<!-- Contenu principal -->
<main class="main-content">
    <!-- Page d'accueil -->
    <section class="home" id="home">
        <div class="container">
            <!-- Intro -->
            <div class="intro">
                <!-- Image avatar -->
                <img src="<?=ASSETS?>portfolio/img/avatar.png" alt="Guen" />
                <!-- Information -->
                <h1>Freddy Guenengafo</h1>
                <span>Je suis <span class="info-text">développeur</span> </span>
                <!-- Réseaux sociaux -->
                <ul class="social-icons">
                    <li><a href="#"><i class="lni lni-github-original"></i></a></li>
                    <li><a href="#"><i class="lni lni-twitter-original"></i></a></li>
                    <li><a href="#"><i class="lni lni-facebook-messenger"></i></a></li>
                </ul>
                <!-- Boutons -->
                <div>
                    <a href="#" class="btn btn-default">Me contacter</a>
                </div>
                <!-- Défiler vers le bas -->
                <div class="defiler-bas">
                    <a href="#" class="emballage-souris">
                        <span>Vers le bas</span>
                        <span class="souris">
                            <span class="molette"></span>
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- *******Page About******* -->
    <section class="about section" id="about">
        <div class="container">
            <!-- Titre -->
            <h2 class="section-tittle padd-15">Qui suis-je ?</h2>
            <div class="row">
                <div class="about-img padd-15">
                    <!-- Image -->
                    <img src="<?=ASSETS?>portfolio/img/avatar.png" alt="Guen" class="image"/>
                </div>
                <div class="about-content padd-15">
                    <div class="arrondi">
                        <div class="row">
                            <div class="about-text padd-15">
                                <!-- A propos text-->
                                <p>Je m'appelle Freddy, je suis développeur à Toulouse (France). J'occupe le poste
                                d'ingénieur de développement informatique au sein d'Atos depuis Mars 2019. J'ai une
                                expérience dans la conception, la programmation des applications et je suis un passionné
                                des technologies du web.</p>
                                <div>
                                    <a href="#" class="btn btn-default">Télécharger mon CV</a>
                                </div>
                            </div>
                            <div class="competences padd-15">
                                <div class="row">
                                    <!-- item compétence -->
                                    <div class="competence-item">
                                        <h4>Développement</h4>
                                        <div class="progress">
                                            <div class="progress-in" style="width: 80%; background-color: rgba(31,232,85,0.68)"></div>
                                            <div class="competence-pourcentage">80%</div>
                                        </div>
                                    </div>
                                    <!-- item compétence -->
                                    <div class="competence-item">
                                        <h4>Conception</h4>
                                        <div class="progress">
                                            <div class="progress-in" style="width: 75%; background-color: rgba(229,232,86,0.81)"></div>
                                            <div class="competence-pourcentage">75%</div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Aficchage des statiques des traveaux -->
            <div class="row">
                <!-- Stat item -->
                <div class="stat-item padd-15">
                    <i class="lni lni-code-alt"></i>
                    <div class="details">
                        <h3>15</h3>
                        <p>Projets</p>
                    </div>
                </div>
                <!-- Stat item -->
                <div class="stat-item padd-15">
                    <i class="lni lni-share-alt-1"></i>
                    <div class="details">
                        <h3>18</h3>
                        <p>Technologies</p>
                    </div>
                </div>
                <!-- Stat item -->
                <div class="stat-item padd-15">
                    <i class="lni lni-users"></i>
                    <div class="details">
                        <h3>2</h3>
                        <p>Grands Clients</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

</main>


<!--On charge le footer-->
<?php $this->view("portfolio/footer", $data); ?>
