
<!--On charge le header-->
<?php $this->view("portfolio/header", $data); ?>

<!-- Contenu principal -->
<main class="main-content">
    <!-- Page d'accueil -->
    <section class="home" id="home">
        <div class="container">
            <!-- Intro -->
            <div class="intro">
                <!-- Image avatar -->
                <img src="<?=ASSETS?>portfolio/img/avatar.png" alt="Guen" />
                <!-- Information -->
                <h1>Freddy Guenengafo</h1>
                <span>Je suis <span class="info-text">développeur</span> </span>
                <!-- Réseaux sociaux -->
                <ul class="social-icons">
                    <li><a href="#"><i class="lni lni-github-original"></i></a></li>
                    <li><a href="#"><i class="lni lni-twitter-original"></i></a></li>
                    <li><a href="#"><i class="lni lni-facebook-messenger"></i></a></li>
                </ul>
                <!-- Boutons -->
                <div>
                    <a href="#" class="btn btn-default">Me contacter</a>
                </div>
                <!-- Défiler vers le bas -->
                <div class="defiler-bas">
                    <a href="#" class="emballage-souris">
                        <span>Vers le bas</span>
                        <span class="souris">
                            <span class="molette"></span>
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- *******Page About******* -->
    <section class="about section" id="about">
        <div class="container">
            <!-- Titre -->
            <h2 class="section-title padd-15">Qui suis-je ?</h2>
            <div class="row">
                <div class="about-img padd-15">
                    <!-- Image -->
                    <img src="<?=ASSETS?>portfolio/img/avatar.png" alt="Guen" class="image"/>
                </div>
                <div class="about-content padd-15">
                    <div class="arrondi">
                        <div class="row">
                            <div class="about-text padd-15">
                                <!-- A propos text-->
                                <p>Je m'appelle Freddy, je suis développeur à Toulouse (France). J'occupe le poste
                                    d'ingénieur de développement informatique au sein d'Atos depuis Mars 2019. J'ai une
                                    expérience dans la conception, la programmation des applications et je suis un passionné
                                    des technologies du web.</p>
                                <div>
                                     <a href="#" class="btn btn-default">Télécharger mon CV</a>
                                </div>
                            </div>
                            <div class="competences padd-15">
                                <div class="row">
                                    <!-- item compétence -->
                                    <div class="competence-item">
                                        <h4>Développement</h4>
                                        <div class="progress">
                                            <div class="progress-in" style="width: 80%; background-color: rgba(31,232,85,0.68)"></div>
                                            <div class="competence-pourcentage">80%</div>
                                        </div>
                                    </div>
                                    <!-- item compétence -->
                                    <div class="competence-item">
                                        <h4>Conception</h4>
                                        <div class="progress">
                                            <div class="progress-in" style="width: 75%; background-color: rgba(229,232,86,0.81)"></div>
                                            <div class="competence-pourcentage">75%</div>
                                        </div>
                                    </div>

                                </div>
                                <!-- Aficchage des statiques des traveaux -->
                                <div class="row">
                                    <!-- Stat item -->
                                    <div class="stat-item padd-15">
                                        <i class="lni lni-code-alt"></i>
                                        <div class="details">
                                            <h3>15</h3>
                                            <p>Projets</p>
                                        </div>
                                    </div>
                                    <!-- Stat item -->
                                    <div class="stat-item padd-15">
                                        <i class="lni lni-share-alt-1"></i>
                                        <div class="details">
                                            <h3>18</h3>
                                            <p>Technologies</p>
                                        </div>
                                    </div>
                                    <!-- Stat item -->
                                    <div class="stat-item padd-15">
                                        <i class="lni lni-users"></i>
                                        <div class="details">
                                            <h3>2</h3>
                                            <p>Articles</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- *******Expériences******* -->
    <section class="section" id="experience">
        <div class="container">
            <!-- Titre de la section -->
            <h2 class="section-title padd-15">Expérience</h2>
            <div class="row">
                <!-- Education -->
                <div class="etudes padd-15">
                    <div class="row">
                        <div class="timeline-box">
                            <div class="timeline">
                                <!-- timeline item -->
                                <div class="timeline-item">
                                    <i class="lni lni-graduation timeline-icon"></i>
                                    <h3 class="timeline-date">
                                        <i class="lni lni-calendar"></i> 2019 - Présent
                                    </h3>
                                    <h3 class="timeline-title">Academic Degree</h3>
                                    <p class="timeline-text">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise
                                        en page avant impression. </p>
                                </div>
                                <!-- timeline item -->
                                <div class="timeline-item">
                                    <i class="lni lni-graduation timeline-icon"></i>
                                    <h3 class="timeline-date">
                                        <i class="lni lni-calendar"></i> 2017 - 2013
                                    </h3>
                                    <h3 class="timeline-title">Bachelor's Degree</h3>
                                    <p class="timeline-text">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise
                                        en page avant impression. </p>
                                </div>
                                <!-- timeline item -->
                                <div class="timeline-item">
                                    <i class="lni lni-graduation timeline-icon"></i>
                                    <h3 class="timeline-date">
                                        <i class="lni lni-calendar"></i> 2013 - 2009
                                    </h3>
                                    <h3 class="timeline-title">Honours Degree</h3>
                                    <p class="timeline-text">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise
                                        en page avant impression. </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- expérience -->
                <div class="experience padd-15">
                    <div class="row">
                        <div class="timeline-box">
                            <div class="timeline">
                                <!-- timeline item -->
                                <div class="timeline-item">
                                    <i class="lni lni-briefcase timeline-icon"></i>
                                    <h3 class="timeline-date">
                                        <i class="lni lni-calendar"></i> 2019 - Présent
                                    </h3>
                                    <h3 class="timeline-title">Développeur web</h3>
                                    <p class="timeline-text">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise
                                        en page avant impression. </p>
                                </div>
                                <!-- timeline item -->
                                <div class="timeline-item">
                                    <i class="lni lni-briefcase timeline-icon"></i>
                                    <h3 class="timeline-date">
                                        <i class="lni lni-calendar"></i> 2017 - 2013
                                    </h3>
                                    <h3 class="timeline-title">Développeur  Front-End</h3>
                                    <p class="timeline-text">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise
                                        en page avant impression. </p>
                                </div>
                                <!-- timeline item -->
                                <div class="timeline-item">
                                    <i class="lni lni-briefcase timeline-icon"></i>
                                    <h3 class="timeline-date">
                                        <i class="lni lni-calendar"></i> 2013 - 2009
                                    </h3>
                                    <h3 class="timeline-title">Développeur Back-End</h3>
                                    <p class="timeline-text">Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise
                                        en page avant impression. </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- *******Projets******* -->
    <section class="projets section" id="projets">
        <div class="container">
            <!-- Section titre -->
            <h2 class="section-title padd-15">Projets</h2>
            <div class="row">
                <div class="projets-filtre padd-15">
                    <div class="projets-filtre-interne">
                        <button type="button" class="active">Tous</button>
                        <button type="button">WebApp</button>
                        <button type="button">Front-End</button>
                        <button type="button">Jeu</button>
                        <button type="button">Mobile</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- Projet item -->
                <div class="projets-item padd-15" >
                    <div class="inner">
                        <div class="thumb">
                            <a href="#"><span class="terme">WebApp</span></a>
                            <a href="#"><img src="<?=ASSETS?>portfolio/img/referentiel_etudiants.png" alt="referentiel"/></a>
                        </div>
                        <div class="details">
                            <h3 class="title"><a href="#">Reférentiel Etudiants</a></h3>
                            <ul class="meta">
                                <li>Java Spring/Boot</li>
                                <li>Angular</li>
                                <li>PostgreSQL</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Projet item -->
                <div class="projets-item padd-15" >
                    <div class="inner">
                        <div class="thumb">
                            <a href="#"><span class="terme">Mobile, Jeu</span></a>
                            <a href="#"><img src="<?=ASSETS?>portfolio/img/capitales_monde.png" alt="capitales"/></a>
                        </div>
                        <div class="details">
                            <h3 class="title"><a href="#">Les capitales du monde</a></h3>
                            <ul class="meta">
                                <li>Flutter</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Projet item -->
                <div class="projets-item padd-15" >
                    <div class="inner">
                        <div class="thumb">
                            <a href="#"><span class="terme">Front-End</span></a>
                            <a href="#"><img src="<?=ASSETS?>portfolio/img/front_end.png" alt="Guen"/></a>
                        </div>
                        <div class="details">
                            <h3 class="title"><a href="#">IHM responsive</a></h3>
                            <ul class="meta">
                                <li>HTML/CSS</li>
                                <li>JavaScript</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Projet item -->
                <div class="projets-item padd-15" >
                    <div class="inner">
                        <div class="thumb">
                            <a href="#"><span class="terme">WebApp</span></a>
                            <a href="#"><img src="<?=ASSETS?>portfolio/img/front_end.png" alt="Guen"/></a>
                        </div>
                        <div class="details">
                            <h3 class="title"><a href="#">API</a></h3>
                            <ul class="meta">
                                <li>Spring/Boot</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Projet item -->
                <div class="projets-item padd-15" >
                    <div class="inner">
                        <div class="thumb">
                            <a href="#"><span class="terme">Front-End</span></a>
                            <a href="#"><img src="<?=ASSETS?>portfolio/img/front_end.png" alt="Guen"/></a>
                        </div>
                        <div class="details">
                            <h3 class="title"><a href="#">Test</a></h3>
                            <ul class="meta">
                                <li>HTML/CSS</li>
                                <li>JavaScript</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Projet item -->
                <div class="projets-item padd-15" >
                    <div class="inner">
                        <div class="thumb">
                            <a href="#"><span class="terme">Jeu, Mobile</span></a>
                            <a href="#"><img src="<?=ASSETS?>portfolio/img/front_end.png" alt="Guen"/></a>
                        </div>
                        <div class="details">
                            <h3 class="title"><a href="#">Autres</a></h3>
                            <ul class="meta">
                                <li>Flutter</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--=============== Contact ===============-->
    <section class="contact section" id="contact">
        <div class="container">
            <!-- section title -->
            <h2 class="section-title padd-15">Contact us</h2>
            <div class="row">
                <!-- contact box -->
                <div class="contact-box padd-15">
                    <div class="contact-data">
                        <!-- contact information -->
                        <div class="contact-information">
                            <h3 class="contact-subtitle">Pour m'appeler</h3>
                            <span class="contact-description">
                                    <i class="lni lni-phone contact-icon"></i>
                                    +33 7 68 49 32 02
                                </span>
                        </div>
                        <!-- contact information -->
                        <div class="contact-information">
                            <h3 class="contact-subtitle">Email</h3>
                            <span class="contact-description">
                                    <i class="lni lni-user contact-icon"></i>
                                    freddy_guenengafo@yahoo.fr
                                </span>
                        </div>
                    </div>
                </div>
                <!-- contact form -->
                <form action="" class="contact-form padd-15">
                    <div class="contact-inputs">
                        <!-- contact content -->
                        <div class="contact-content">
                            <input type="email" class="contact-input">
                            <label for="" class="contact-label">Email</label>
                            <span></span>
                        </div>
                        <!-- contact content -->
                        <div class="contact-content">
                            <input type="text" class="contact-input">
                            <label for="" class="contact-label">Objet</label>
                            <span></span>
                        </div>
                        <!-- contact content -->
                        <div class="contact-content contact-area">
                            <textarea name="" id="" cols="30" rows="10" class="contact-input"></textarea>
                            <label for="" class="contact-label">Message</label>
                            <span></span>
                        </div>
                    </div>
                    <a href="#" class="btn btn-default">Envoyer</a>
                </form>
            </div>
        </div>
    </section>

    <!--=============== Footer ===============-->
    <footer class="footer">
        <div class="container">
            <div class="footer-text padd-15">
                <p>&copy; Guen | 2022 Tous droits réservés</p>
            </div>
        </div>
    </footer>
</main>


<!--On charge le footer-->
<?php $this->view("portfolio/footer", $data); ?>
